apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mthmlops
  namespace: argocd
spec:
  project: mthmlops
  source:
    repoURL: https://github.com/baylib/mthmlops-infra.git
    targetRevision: main
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

