apiVersion: v1
kind: Pod
metadata:
  name: nfs-server
spec:
  containers:
    - name: nfs-server
      image: itsthenetwork/nfs-server-alpine:latest
      securityContext:
        privileged: true
      args:
        - /nfs
      volumeMounts:
        - name: nfs-data
          mountPath: /nfs
      ports:
        - containerPort: 2049
  volumes:
    - name: nfs-data
      hostPath:
        path: /nfs-share
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-service
spec:
  selector:
    app: nfs-server
  ports:
    - port: 2049
      targetPort: 2049
      protocol: TCP
