apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-mthmlops
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: nfs-service.nfs.svc.cluster.local
    path: /nfs
