apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-mthmlops
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /nfs-share
    type: Directory
