apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kfp-addons
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: mthmlops
  source:
    repoURL: https://github.com/baylib/mthmlops-infra.git
    targetRevision: main
    path: kubeflow/addons/
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

