apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kfp-cluster-resources
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: mthmlops
  source:
    repoURL: https://github.com/kubeflow/pipelines.git
    targetRevision: 2.5.0 
    path: manifests/kustomize/cluster-scoped-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

