apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-pipelines
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: mthmlops
  source:
    repoURL: https://github.com/kubeflow/pipelines.git
    targetRevision: 2.5.0
    path: manifests/kustomize/env/platform-agnostic
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: "rbac.authorization.k8s.io"
      kind: Role
      name: pipeline-runner
      namespace: kubeflow
      jsonPointers:
        - /rules/-
      jqPathExpressions:
        - '.rules[] | select(.resources == ["workflowtaskresults"])'
