apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-server
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: mthmlops
  source:
    repoURL: https://github.com/baylib/mthmlops-infra.git
    targetRevision: main
    path: nfs-server/
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

