apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-server-provisioner
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: mthmlops
  source:
    repoURL: 'https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/'
    chart: nfs-subdir-external-provisioner
    targetRevision: 4.0.2
    helm:
      values: |
        nfs:
          server: localhost
          path: /exports
        storageClass:
          name: nfs
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nfs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true