apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mthmlops-app
  namespace: argocd
spec:
  project: mthmlops
  source:
    chart: svm-api-helm
    repoURL: registry-1.docker.io/mthmlops
    targetRevision: 0.1.0
    helm:
      # releaseName: mthmlops-svm-api
      valuesObject:
        modelVersion: 0.0.2
  destination:
    server: https://kubernetes.default.svc
    namespace: mthmlops-prod
  syncPolicy:
    automated:
      prune: true  # Enable auto-pruning
      selfHeal: true  # Auto-correct drift
    syncOptions:
      - CreateNamespace=true  # Auto-create target namespace