apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mthmlops-app
  namespace: argocd
spec:
  destination:
    namespace: mthmlops-prod
    server: https://kubernetes.default.svc
  project: mthmlops
  source:
    chart: svm-api-helm
    helm:
      valuesObject:
        modelVersion: 0.0.7
    repoURL: registry-1.docker.io/mthmlops
    targetRevision: 0.1.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
