apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mthmlops-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: nfs-pv
  storageClassName: ""
